version: "3.0"

services:
  grafana:
    container_name: "sasaki77-archiverappliance-datasource"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.2.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    networks:
      - archapplnet
    ports:
      - 3000:3000/tcp
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/sasaki77-archiverappliance-datasource
      - grafana-storage:/var/lib/grafana
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.sasaki77-archiverappliance-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: sasaki77-archiverappliance-datasource

  mariadb:
    hostname: mariadb
    image: mariadb
    networks:
      - archapplnet
    environment:
      MYSQL_ROOT_PASSWORD: archappl
      MYSQL_DATABASE: archappl
      MYSQL_USER: archappl
      MYSQL_PASSWORD: archappl
    volumes:
      - aad-db:/var/lib/mysql
      - ./devenv/sql:/docker-entrypoint-initdb.d

  archappl:
    hostname: archappl
    image: ghcr.io/archiver-appliance/epicsarchiverap:singletomcat-a81b5e4
    depends_on:
      - mariadb
    networks:
      - archapplnet
    ports:
      - 8080:8080
    environment:
      ARCHAPPL_APPLIANCES: /usr/local/tomcat/archappl_conf/singleappliances.xml
    volumes:
      - ./devenv:/usr/local/tomcat/archappl_conf
      - aad-storage:/usr/local/tomcat/storage/

  ioc:
    image: ghcr.io/epics-containers/epics-base-developer:7.0.8ad3
    networks:
      - archapplnet
    volumes:
      - ./devenv:/home
    stdin_open: true
    tty: true
    command: ["softIocPVA", "-d", "/home/test.db"]

networks:
  archapplnet:

volumes:
  aad-storage:
  aad-db:
  grafana-storage:
