name: build-publish-docs.yml
on:
  workflow_dispatch:
  push:
    paths:
    - 'docs/**'
jobs:
  build-publish-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies 
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Build Sphinx Documentation
        run: | 
          cd docs
          make html
      - name: Deploy Documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

