name: build-publish-docs.yml
on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Build Sphinx Documentation
        run: |
          sphinx-multiversion docs docs/_build/html
          cp docs/ghp_assets/index.html docs/_build/html/index.html
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
