name: build-and-test.yml
on: [push]
jobs:
  build-and-test-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:ci
      - name: Build frontend
        run: yarn build

      - name: Setup Go environment
        uses: actions/setup-go@v3

      - name: Run Go tests using Mage
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: vtest

      - name: Build backend
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: -v buildAll
