name: Nightly Release

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  nightly-builds:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      ZIP_NAME: archiverappliance-datasource
      TAG_NAME: nightly
      NODE_VERSION: '24'
      GO_VERSION: 'stable'

    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: vtest

      - name: Build backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: -v buildAll

      - name: Build Frontend
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Prepare Release Artifact
        run: |
          REPO_DIRECTORY=${PWD##*/}
          pushd ../
          zip -r $REPO_DIRECTORY/${{ env.ZIP_NAME }}.zip $REPO_DIRECTORY -x @$REPO_DIRECTORY/exclude.txt
          popd

      - name: Update Tag and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Force update the 'nightly' tag to the current commit
          git tag -f ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }} --force

          # Try to update existing release, otherwise create a new one
          gh release upload ${{ env.TAG_NAME }} ./${{ env.ZIP_NAME }}.zip --clobber || \
          gh release create ${{ env.TAG_NAME }} ./${{ env.ZIP_NAME }}.zip --prerelease

          gh release edit ${{ env.TAG_NAME }} \
            --title "Nightly Build (${{ env.TAG_NAME }})" \
            --notes "Automated build generated on $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
